name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Download repo
      uses: actions/checkout@v4

    - name: instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: verify code
      run: |
        python -m compileall .
